### ISSUE TITLE
Update protostub with state machine 

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-msg-node-nodejs#12]
As specified [here](https://github.com/reTHINK-project/specs/blob/master/messaging-framework/stub-specification.md#state-machine)

Tests can be performed with "dev-protostub-state-machine" branch of the runtime-core branch.

Vertx protostub was already updated with this state machine implementation also in a "dev-protostub-state-machine" branch.

**Comment by jboulmal** [comment]
done
