### ISSUE TITLE
 NodeJS MN: update subscribe/unsubscribe message format according to spec.

### ISSUE THREAD

**Issue by sdruesedow** [reTHINK-project/dev-msg-node-nodejs#29]
instead of "body.subscribe" or "body.unsubscribe" the latest spec uses "body.resources" for all types of subscribe/unsubsribe messages. (see [spec.](https://github.com/reTHINK-project/specs/blob/master/messages/data-sync-messages.md#synchronisation-management-by-message-node) )

The NodeJS MN shall be updated accordingly.

**Comment by sdruesedow** [comment]
This issue is relevant for D6.4. If not solved then the conformance tests will report missing features for the NodeJS node.

**Comment by sdruesedow** [comment]
I'm documenting the situation for D6.4 as it is

**Comment by emmelmann-fokus** [comment]
Hi,

From WP-6 perspective, I am fine with this as we have to only assess the work in WP-6 and provide feedback to the technical WPs.

But from an overall perspective, this will raise issues in the final review, i.e., 
  * that a technical issue, that features having had worked before, were not working any more,
  * that this situation had been reported to the technical WPs, and
  * that a solution was not found within a month, nor was there a documented follow-up discussion.

Just my two cents.

**Comment by jboulmal** [comment]
Fixed, re-open if needed

**Comment by sdruesedow** [comment]
not tested and confirmed yet --> re-opening
