### ISSUE TITLE
NodeJS MN crashes during domain-registry tests cases

### ISSUE THREAD

**Issue by sdruesedow** [reTHINK-project/dev-msg-node-nodejs#30]
During the test execution of the MN conformance tests in [registration.spec.js](https://github.com/reTHINK-project/specs/blob/master/tests/msg-node/test/registration.spec.js) the NodeJS MN crashes with following log:

```
nodejs      | [2017-06-07 08:41:05.714] [INFO] server - [C->S] new event :  {"id":1,"type":"read","from":"hyperty-runtime://localhost/1/registry","to":"domain://registry.localhost","body":{"resource":"user://google.com/openIdTest10"}}
nodejs      | [2017-06-07 08:41:05.714] [INFO] server - [PEP] PDP PolicySet 1/ Policy 2/ Rule 3 determined to permit. resulted from allow-overrides algorithm of PDP PolicySet 1
nodejs      | [2017-06-07 08:41:05.714] [INFO] server - [Domain-Registry-Manager], [ domain://registry.localhost/ ]: handle registry message :
nodejs      |  { id: 1,
nodejs      |   type: 'read',
nodejs      |   from: 'hyperty-runtime://localhost/1/registry',
nodejs      |   to: 'domain://registry.localhost',
nodejs      |   body: { resource: 'user://google.com/openIdTest10', auth: true } }
nodejs      | [2017-06-07 08:41:05.715] [INFO] server - msg.msg.type.toLowerCase() is: read
nodejs      | [2017-06-07 08:41:05.721] [INFO] server - [ domain://registry.localhost/ ] Reply from domain registry :
nodejs      |   { code: 404, description: undefined }
nodejs      | undefined:1
nodejs      | undefined
nodejs      | ^
nodejs      | 
nodejs      | SyntaxError: Unexpected token u in JSON at position 0
nodejs      |     at Object.parse (native)
nodejs      |     at parseObj (/usr/src/app/src/main/components/rethink/DomainRegistryManager.js:50:25)
nodejs      |     at registryConnector.processMessage (/usr/src/app/src/main/components/rethink/DomainRegistryManager.js:71:23)
nodejs      |     at /usr/src/app/node_modules/dev-registry-domain/connector/src/hyperty.js:51:5
nodejs      |     at /usr/src/app/node_modules/async/retry.js:149:26
nodejs      |     at Request._callback (/usr/src/app/node_modules/dev-registry-domain/connector/src/js-request.js:49:14)
nodejs      |     at Request.self.callback (/usr/src/app/node_modules/request/request.js:188:22)
nodejs      |     at emitTwo (events.js:106:13)
nodejs      |     at Request.emit (events.js:191:7)
nodejs      |     at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1171:10)
nodejs exited with code 1
```

**Comment by sdruesedow** [comment]
This issue is relevant for D6.4.

**Comment by jboulmal** [comment]
I guess this due to new specs.
When is the deadline @sdruesedow ?

**Comment by sdruesedow** [comment]
afaik the D6.4 shall be ready mid of June. I need to repeat the tests and document them, so I think next Tuesday latest would be OK from my side. Do you think it's feasible?

**Comment by jboulmal** [comment]
OK

**Comment by sdruesedow** [comment]
any updates?

**Comment by sdruesedow** [comment]
I'm documenting the situation for D6.4 as it is

**Comment by emmelmann-fokus** [comment]
Hi,

From WP-6 perspective, I am fine with this as we have to only assess the work in WP-6 and provide feedback to the technical WPs.

But from an overall perspective, this will raise issues in the final review, i.e., 
  * that a technical issue, that features having had worked before, were not working any more,
  * that this situation had been reported to the technical WPs, and
  * that a solution was not found within a month, nor was there a documented follow-up discussion.

Just my two cents.

**Comment by jboulmal** [comment]
sorry for the delay reply, 
Last week I was in Oulu, for EuCNC event.
I'm working on the issue right now, could please @sdruesedow guide me on how to test it locally ?

**Comment by sdruesedow** [comment]
Are there some updates available? With the available develop-branch version the MN is still crashing during the registry tests.

**Comment by sdruesedow** [comment]
The currently available MN still crashes during the registry testcases due to JSON parsing trouble. This is now documented in D6.4.

**Comment by FredLuart** [comment]
Issue reproducted : seems to be linked with commit from @Heriam  : https://github.com/reTHINK-project/dev-msg-node-nodejs/commit/bf20ec1de279ff9c59b396d9f2a0b76000eaeea3#diff-ddd9b51315ce0bbd46ea1d02a46f0a8d

**Comment by Heriam** [comment]
@FredLuart yes I tried to solve the JSON parsing issue before and it worked. No idea why it produces new issues since I have not worked on it for a period. Maybe try to undo this commit (remove my change) to see if it works.

**Comment by sdruesedow** [comment]
It seems that the error happens, when the registry returns the value "undefined" for the description of a 404 response. Parsing of "undefined" fails and the MN crashes.
In addition to reverting the commit I suggest to add a code snippet like this one on the registry response before returning it:
```
      try {
        body.value = JSON.parse(body.value);
      } catch (e) {
        console.log("[RegistryInterface] CALLBACK: unable to parse body.value \n", body.value);
      }
```
because the registry started at some point in the past to return a stringified JSON instead of a JSON Object in the "body.value" attribute of its response message.

**Comment by FredLuart** [comment]
@sdruesedow I have just pushed a patch on develop branch. I still have 1 test failed on :  "receive registration status updates". I am checking the issue.
Let me know if you need some help about D6.4

**Comment by sdruesedow** [comment]
Hi @FredLuart. Great - Thanks! This test is expected to fail, because it is not yet supported by the RegistryConnector and/or the Registry itself (I'm not sure about that). But it is already in the spec and therefore part of the testcases.
I'll run the tests again and update D6.4 accordingly tomorrow morning. Thanks!

**Comment by sdruesedow** [comment]
@FredLuart I just updated and ran the tests again and can confirm that they are running successfully now. I'll update D6.4 accordingly. Thanks a lot!

**Comment by emmelmann-fokus** [comment]
@sdruesedow @FredLuart -- Thank you so much for solving the remaining issues with the code.  That was the last missing piece for a successful WP6 closure.

**Comment by AnastasiusGavras** [comment]
Indeed, I would like to second the appreciation for solving the issue.
